# Generated by Django 4.2.1 on 2023-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='grown_from',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SEEDLING', 'Seedling'), ('CUTTING', 'Cutting'), ('FULLSIZE', 'Full Size')], default='Full Size', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVING ROOM', 'Living Room'), ('MUDROOM', 'Mud Room'), ('FRONT STEPS', 'Front Steps'), ('BACK DECK', 'Back Deck'), ('BACK GARDEN', 'Back Garden'), ('FRONT GARDEN', 'Front Garden')], default='Mud Room', max_length=100),
        ),
    ]
