# Generated by Django 4.2.1 on 2023-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_plant_grown_from_alter_plant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='scientific',
            field=models.CharField(default='', max_length=150),
        ),
    ]
