# Generated by Django 4.2.1 on 2023-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_plant_scientific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVING RM', 'Living Room'), ('MUDROOM', 'Mud Room'), ('FR STEPS', 'Front Steps'), ('BACK DECK', 'Back Deck'), ('BACK GARDEN', 'Back Garden'), ('FR GARDEN', 'Front Garden')], default='Mud Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='schedule',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
