# Generated by Django 4.2.1 on 2023-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_plant_location_alter_plant_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='schedule',
            field=models.PositiveIntegerField(blank=1, default=1),
        ),
    ]
